swagger: "2.0"
info:
  version: "0.0.1"
  title: CoSpaces Backend
host: localhost:10010
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    # x-swagger-router-controller: hello_world

    get:
      tags: 
        - users
      description: Returns all users
      # operationId: 
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllUsers"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
    
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        example: Error Message

  AllUsers:
    type: array
    items:
      $ref: "#/definitions/UserSlim"

  UserSlim:
    properties:
      id:
        type: integer
        example: 1000
      username:
        type: string
        example: sebastiantf
      email:
        type: string
        example: sebastian.tharakan97@gmail.com
      profile_picture:
        type: string
        example: https://domain.com/path/to/profilepic
